apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:XY32zzqiTJBrPN+5T0GDs/pMd7LsYJ5zWqdC56HhlH/Lb1UKd0xdRuXZnIv6pqpXDY1O34Ks66xARGohx2TKctoB54WzhGvhi+W2+UrDlevBjhCau/HCuJl47n/mjSKwEZjcbyePKI53nUczYWPKzq7sP/vHBrDKFo2V2eyF2gFikOkRroOe2579ZkVolwMEEkmFVzRqHZr9qTgYt/rhx9Q1i0ZRFbiAQcc4j5xM3BoHSvl/Tk55OXPIlccxzQShsCvoikZgM35lxp/jAHhYzkFcUVaBHZ6wTrqdYuwcwV58sMqokY9KC83q5bTR+Hl8If6Li/vMSnDI+IUdo0YmZzX9NT+bTfirtyJMjh8UQmtneuYK6s46XqgwP5G8+BGI,iv:7dRWTLWNckDdUC+5cQF3pgx/UaZOmG1gX19kshaXjys=,tag:2Ap+TL/LHjFNLNI2Vfgg7g==,type:str]
    identity.pub: ENC[AES256_GCM,data:VmUU9o3X7Tga1LKpYe967f8+wdT17ai75JWVfsW4ZbNkmWOkv8dzYzShsCRrX7OozskKBa2xgt+i1FKceIwy9U3iVYjBsocw0qf1CXJ/E8zEfD2jbQ+IsBvMxLuH7PVpq5jEuYfCYeanGrfUxFMoxPsbSrUFDM2YWOd3eC1VKAli5ryWFS2x/9ToxRkbFXvhH4Xu6u0xeBD8CAQzSt6/Kn6Xgt+a6oU798R/QlDKSInQ+Fh0Vs7ZCaLdxGGuiKVBtWuEL6GwUY6Y1vMylg==,iv:IyBCwsEjsstrc7Dsl3TsdD9jwwJmTO5r4GodMjkdtEs=,tag:z6qhiKIXOz2Eq4JjVuMrcQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:qM+lFhfQcH9FfiPUdynzRMnJCvLd/t0M6Lh4wJNNyjix+/R3919KyHV/bzdHQaEVYEqr8DuOi/zWhejLC04g2EHDOLobt7n1xYb/aTLjaPXclqBrGJuU7PaJEnheHBOoLlxM4Rw8okZi6JvQsRBe9eCAmgp1zh/6/9OYntu7t8mJLDUaxSKBgXxDMzLdfnLofLv+2gm4K00w1dsR0bTblUoa+Oh2PjbnTIfS,iv:uWIhZgkkLaKQLX0cusGpzo1Rbl+rbx5JUOWWnZu+P1o=,tag:HUpVoZMsfEDOm0Y7m7Qd+w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age16ekkh8rjlfe0ddgygp8w0myrma8e2q2q5vr5ekhvvvg9patsf48qr4u6l4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0LzRYczhsYzZSbDVYUm12
            YWVLSmdJRFA2TCtzeHJVa1JrUktSbDllTmxRClhUV3pzQmF6eVVDaDgzYTJwU2ZC
            eG1ncVBmYytDcmxkZ1ZBWHBZRWQxemsKLS0tIDZ1K1pKVEZpdFFsVW9hbnhwSnBL
            OGJyaWhBUm85NmE3RVJFK1FHL3F3QlUKHcHXzqNA+4jKD4fcUO8rrHs1BxXOxqwo
            tOBaxUI7YyMfyOuWOOPoh5OTEdrCCahYnVX49tZWxNaXd5Sz/SvGNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T17:06:07Z"
    mac: ENC[AES256_GCM,data:ANMVqGKo4hyglTgn72FRJfWKlB5a1Oaw3j9PjvOX7wG/2pvwVeGAVrSF8fUhOcoHHSvk88hZ3hYaBDckVnv6JcD3L/08vqz+PF8kslopKf4f0ZXtBLBRC2RcbBJciyu1cQOySnv+Njva/BY2hxA1SYAq0B0TPyw0wWIyZx3gvbQ=,iv:rfair2YGymOXEUrymtC7+bZwxRdOIYLI0qOhz7qc6UE=,tag:7qd4md9sflLtJ282YnbqiA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
