apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:QuHMmn7lPNYKmCHj4n1hpD1x4U2YNhtu6cdVekzrf6xkgodiHYdW5XMb1+9wnk1H63/JmYkbzjfNdOSgH4Q0HLsDRaEQFfbyAwIWsbbZDai7j2vTxqW9nhcAFqH4N9gu/otI4+iyDmfg/1w/x0ODldiafbZ8XRKGE4cph6SO/HXHS9Tr6xt2Jy2kNANw3ZovftwjfCOFgwOJh9Aq0Cox9LVVlqkpLvVaeqpkb5pHXDPppZSbExub+jhBqAl/OCyExr9oWVT/7sGbh7wqG7RE4j+7zDtMqRNwTXOtZmMypab4x13gvhYIjtzAdMgHwIDGhMNO0HcsrOMslk7Har1JkREE8C2FH9jNTCipRZxGi2HvIuV3hV11pVzMiqDxZbJT,iv:SgOr9d9UCtZ9y3yQ5JAtb307BVdkwmV/XWrwU+RkCM0=,tag:rFK9YTotMz1e1OAt7ptK6w==,type:str]
    identity.pub: ENC[AES256_GCM,data:D/t/fop+gSjlBMNaS9XAjkrYbRP72RLZb6eAPqk1TiMoZ3WhavT/+lggVoa/L1VFsJy8q/JQF9Mtu6gk0RB7E/OCMApEn+sqhXyPcV4Kqao31BTkCRQXvcjS6RJJ9MVZ6keSQrLqxbq/qhTIvurM/Yb3csmt0qDYRPNJYatqHmUZXRNmj8ncOMI/GHgWyatZLUl728Ka9DLT3P90V0MgOU+G2arKha++/TFzW+RL1D9VK398AC3KHbK3QwYcm9kXfRejOr2qCzXlq/cD0Q==,iv:dNyqEHiZN/LYULyaGSD7j+0FLY/jXMUVHa9pePhHPjg=,tag:gDDraulzh2biE3Okb33irA==,type:str]
    known_hosts: ENC[AES256_GCM,data:8CKEkZ11H0uJQHSGmf+6aJRJaXEqzq/HqAfQjVPjwVSOw/xLQtqBISptuJYYPbUnSRv25xNVkJdglp/FR0JSiSmH8OQ+UoPflTeH5W9KXoOwV1UFt/06Nm0CS+511gbXq3EEdsDifUhnvkVmNGyrVoVZdDiaBXAf0T10lA15VVL8lcYmt2/Lj88ESVu77XDvIPjcC5fyuQkNtpjs6Iu0RzCCTr4hNF6V7N5+,iv:qgjC7WuPNgjZ5irLY+B7URlgrV1sT3R4RKg8F9onbPA=,tag:cW4eIrJxkFCI5z9tfeLKew==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age16ekkh8rjlfe0ddgygp8w0myrma8e2q2q5vr5ekhvvvg9patsf48qr4u6l4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSUFVCdlFTS0ptaVhjQkRq
            MFBXVWlFek1ER2JWZmNzYVlDNGNLaEVDNlRjClhIR2Q3T0VhelV0UEgyczh6eUdP
            ZmVya2h4NTNId2Z6QThVOFBIRVF5eW8KLS0tIG12YTdyQU9aek1ma3d3enNjOStN
            cGRGL3h0YVo2N2sxYjNxSGozdGpBeHcKkf4Z1cu5oQu56xy/lRPn+JeHsMkOUFsV
            2EdrE26HwVRz1HyMyiETbdpHgpp4jrZf6ADzo6XQ6B5KMaIqqSRk6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T13:34:52Z"
    mac: ENC[AES256_GCM,data:po1wGOuBjgnezZHAGtkcuv/J+YMO5zDBXlmEYVmi0a5KB7iW7IZnzNEUH54dLvko0jKz7JX+Hi5z34lkXWqiY+lingkicXYQB5NgybabmjQ2us8R/qoLLsQQPgAS8kjRQG3bR/vEQN14giqXvbn/Nn9rfoPVvuiFCFZQTUEcK/4=,iv:HbNzp3YBRbhgYj7EkA+ELU1oKbigQ83dstoPK/UE6/I=,tag:eNBED6NOtWvc/CHH9kYDQg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
