apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:XWIVqVGKdxAj2oyz/+sdIVr3xI4TnJUlUquN1r024rr1IyVBEwa1S+7htJjVHoUEcPNdu6+EBqI1NpQllbA0WQ6VMf17KOWqV4VuCNATSa3DYTR7Y62p3fRXgNUIrptiUCms3GiZCwF81n91DwFlt5YqkMUBZRXYWrxjNCZyY9AcOsu8/ok16Eh7v6RbXXSN24RM1DxPOQ8L1QvCSbRFApDtPn0X+tsZQcTy1pEKZLRPKNZV9oALHjPHWsw/UqsyZlkf5sh823Wwvg0VhX6U3ZOdtaMeSOSW/wB19GY1bBG6L7MJdLut74Px5AS23g9+kg5475e9vesNQDgwRdnZaN4SrDRc6PzfJB4taA7I6PhhTBR6lEzIbfdR8M70BBaX,iv:A3kBU86PzAJlVtu37vFQ57EFk8naK5W8CThoDAg2gkg=,tag:l404hOHQlP3bh97nXhLiaw==,type:str]
    identity.pub: ENC[AES256_GCM,data:93uCumS58vTPxPU61DzqhnTA057n3KuWS37pdC0RmOE03k8Y8Ti9a0z+2NpfvO71skyEfUuDML3kefPCqO3ffRNcOOZ+Nq5bqAqvX0e77O03qg6d1d7HhlVzaiwS/QFws8hJnxGsWzpjfO2klQ5sC9oLn7KlIBbiJlxIVbLIZ8KcnKa/UEDKpMLblQNcAixFfZ8pQLymYIUSHt9Gi0AVaW84obiKtTMALHWlom4VJQRAo9pelpjjPfRPGTZjbKV/IwSLOUWlwluEISDnBw==,iv:HQOe2Y0lJnJZ0339xXI1CtgFqaLjQtChDZ2BQJGxLhg=,tag:UiNnSKHkJEuyhX+zTnMgaQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:adP5XRBddWTBcuRMk9jGzF8n1J37YXCe7udY+vwcSupFOh/putLEpb1FtSbMaQKNnQUghIQ9ScZWbESbtMX0DbOVVhgKJLejx/ph8AyCiyCHubSagfrPgxACM2buPqqh+Flmn0NeIq12yAzzAZNpGFyPiGjdNkrczlsghu5C6LvVJZcl/NnxvMPCW3f2aX0EOiUZfRPOCQFyw2aTbmEa9bYjO0AdaQm9AU2C,iv:+zegB3KD8ZVVRPR3upWekFzpMVyTIkZfu1FbptoiOLo=,tag:9B8HGiwO5GMR1wXXkp7cwg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age16ekkh8rjlfe0ddgygp8w0myrma8e2q2q5vr5ekhvvvg9patsf48qr4u6l4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZUnd3a3pvcjgrdFppN2RG
            WjE4aU8wdEFZRS9kRElhcVNSTnJ5ZGM2LzFJClFsV2hpT1ZyeHhCMlg0SGg0TmRH
            S05JUnorSkg4SDRWcDB4UWk2KzVMUjgKLS0tIEJQV0VnN1d5NDlTRlFhVC9CamZu
            ZnBvWXVtSDQ3bk1MMW8vR3VCcEhPeUUKKsP8N6hE5LypYTGCiTWFVcXk97ReYeEw
            2gaE2fNwWJl0AAnlrRU6MhHRWYzM5UUJKc2cMTjiHaD+4Z27JKQtjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T15:44:24Z"
    mac: ENC[AES256_GCM,data:OgJ/khSPTTzLm/nnhwroOryMtqqR6eXjgveu++Nv/TJsGcASo4HRG4XVHm0ApxrtXfBQ5WQYR5V8JDfQ/mg6wHzTu52jEopYKgPzFIyWTMimVxMTGclZM5UzvPdiifpsOgzJuCFtwKX7+DUi4+m9AoGAjxTMXwL5RyCKQ2Ti35A=,iv:QdT+0sXXse6cst4JcOOgREei15Nz3GVImAfioeP67jA=,tag:LxIc2SSBsJFleWQu56LsZQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
