---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renovate
  namespace: renovate

spec:
  interval: 15m
  chart:
    spec:
      chart: renovate
      version: 5.16.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    workload:
      main:
        #schedule: "*/3 * * * *"
        podSpec:
          containers:
            main:
              env:
                RENOVATE_CONFIG_FILE: /config/renovate-config.json
                GITHUB_COM_TOKEN: '${GITHUB_RENOVATE_PAT}'
                RENOVATE_TOKEN: '${GITHUB_RENOVATE_PAT}'

    
    configmap:
      config:
        data:
          renovate-config.json: |-
            {
              'repositories': ['ronpao/truecharts-apps-cluster']
            }
    persistence:
      configmap-vol:
        items:
          - key: renovate-config.json
            path: renovate-config.json